In [ ]:
# ===============================
# Install Required Libraries
# ===============================

!pip install -q pandas
!pip install -q numpy
!pip install -q matplotlib
!pip install -q seaborn
!pip install -q plotly
!pip install -q scipy
!pip install -q statsmodels
!pip install -q scikit-learn
!pip install -q openpyxl
!pip install -q xlsxwriter
!pip install -q folium
!pip install -q geopy
!pip install -q streamlit
!pip install -q streamlit-option-menu
!pip install -q pydeck
!pip install -q missingno
!pip install -q ydata-profiling

print("All libraries installed successfully.")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 175.3/175.3 kB 6.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 80.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.4/11.4 MB 86.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 829.3/829.3 kB 17.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 17.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 84.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 32.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 4.7 MB/s eta 0:00:00
All libraries installed successfully.



## Import Required Libraries

Import all Python libraries that will be used throughout the project.

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans

import folium
import missingno as msno

import warnings
warnings.filterwarnings("ignore")

In [ ]:
# =====================================
# Data Manipulation
# =====================================

import pandas as pd
import numpy as np

# =====================================
# Data Visualization
# =====================================

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

# =====================================
# Statistical Analysis
# =====================================

import scipy.stats as stats

# =====================================
# Machine Learning
# =====================================

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# =====================================
# Geospatial Analysis
# =====================================

import folium

# =====================================
# Missing Value Visualization
# =====================================

import missingno as msno

# =====================================
# System Libraries
# =====================================

import os
import warnings
import datetime

warnings.filterwarnings("ignore")

print("Libraries Imported Successfully")

Libraries Imported Successfully

3

## Project Information

Define project details.

In [ ]:
PROJECT_NAME = "Nassau Candy Profitability Analysis"

VERSION = "1.0"

AUTHOR = "Kanishka Sharma"

print("Project :", PROJECT_NAME)
print("Version :", VERSION)
print("Author :", AUTHOR)

Project : Nassau Candy Profitability Analysis
Version : 1.0
Author : Kanishka Sharma

 4

## Create Industry Standard Folder Structure

In [ ]:
folders = [

    "data",

    "clean_data",

    "dashboard",

    "images",

    "models",

    "reports",

    "outputs",

    "notebooks",

    "config",

    "logs"

]

for folder in folders:

    os.makedirs(folder, exist_ok=True)

print("Folder Structure Created Successfully")

Folder Structure Created Successfully

 5

## Mount Google Drive

Connect Google Drive to store datasets and project outputs.

In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os

if os.path.exists("/content/drive"):
    print("✅ Google Drive Connected Successfully")
else:
    print("❌ Google Drive Not Connected")

✅ Google Drive Connected Successfully

In [ ]:
import os

# Project ka main folder
project_path = "/content/drive/MyDrive/Nassau_Candy_Project"

# Folder create karega (agar pehle se hai to error nahi dega)
os.makedirs(project_path, exist_ok=True)

print("✅ Project Folder Created Successfully")
print("📁 Folder Location:", project_path)

✅ Project Folder Created Successfully
📁 Folder Location: /content/drive/MyDrive/Nassau_Candy_Project

In [ ]:
# ==========================================
 # : Create Project Folder Structure
# ==========================================

import os

# Main Project Path
project_path = "/content/drive/MyDrive/Nassau_Candy_Project"

# Industry Standard Folder List
folders = [
    "data",
    "data/raw",
    "data/processed",
    "data/external",
    "images",
    "reports",
    "models",
    "dashboard",
    "outputs",
    "logs",
    "config",
    "notebooks"
]

# Create all folders
for folder in folders:
    folder_path = os.path.join(project_path, folder)
    os.makedirs(folder_path, exist_ok=True)
    print(f"✅ Created: {folder_path}")

print("\n🎉 All project folders created successfully!")

✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/data
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/data/raw
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/data/processed
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/data/external
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/images
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/reports
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/models
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/dashboard
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/outputs
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/logs
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/config
✅ Created: /content/drive/MyDrive/Nassau_Candy_Project/notebooks

🎉 All project folders created successfully!

In [ ]:
# =====================================
#  - Check Files in Raw Folder
# =====================================

import os

raw_path = "/content/drive/MyDrive/Nassau_Candy_Project/data/raw"

print("📂 Files Available:\n")

for file in os.listdir(raw_path):
    print("📄", file)

📂 Files Available:

📄 Nassau Candy Distributor.csv

In [ ]:


import pandas as pd

dataset_path = "/content/drive/MyDrive/Nassau_Candy_Project/data/raw/Nassau Candy Distributor.csv"

df = pd.read_csv(dataset_path)

print("✅ Dataset Loaded Successfully")

✅ Dataset Loaded Successfully

In [ ]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Country/Region,City,State/Province,Postal Code,Division,Region,Product ID,Product Name,Sales,Units,Gross Profit,Cost
0,1,US-2021-103800-CHO-MIL-31000,03-01-2024,30-06-2026,Standard Class,103800,United States,Houston,Texas,77095,Chocolate,Interior,CHO-MIL-31000,Wonka Bar - Milk Chocolate,6.50,2,4.22,2.28
1,2,US-2021-112326-CHO-TRI-54000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,7.50,2,4.90,2.60
2,3,US-2021-112326-CHO-NUT-13000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-NUT-13000,Wonka Bar - Nutty Crunch Surprise,10.47,3,7.47,3.00
3,4,US-2021-112326-CHO-SCR-58000,04-01-2024,01-07-2026,Standard Class,112326,United States,Naperville,Illinois,60540,Chocolate,Interior,CHO-SCR-58000,Wonka Bar -Scrumdiddlyumptious,10.80,3,7.50,3.30
4,5,US-2021-141817-CHO-TRI-54000,05-01-2024,05-07-2026,Standard Class,141817,United States,Philadelphia,Pennsylvania,19143,Chocolate,Atlantic,CHO-TRI-54000,Wonka Bar - Triple Dazzle Caramel,11.25,3,7.35,3.90

In [ ]:
print("Rows and Columns :", df.shape)

Rows and Columns : (10194, 18)

In [ ]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Country/Region', 'City', 'State/Province',
       'Postal Code', 'Division', 'Region', 'Product ID', 'Product Name',
       'Sales', 'Units', 'Gross Profit', 'Cost'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10194 entries, 0 to 10193
Data columns (total 18 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          10194 non-null  int64
 1   Order ID        10194 non-null  object
 2   Order Date      10194 non-null  object
 3   Ship Date       10194 non-null  object
 4   Ship Mode       10194 non-null  object
 5   Customer ID     10194 non-null  int64
 6   Country/Region  10194 non-null  object
 7   City            10194 non-null  object
 8   State/Province  10194 non-null  object
 9   Postal Code     10194 non-null  object
 10  Division        10194 non-null  object
 11  Region          10194 non-null  object
 12  Product ID      10194 non-null  object
 13  Product Name    10194 non-null  object
 14  Sales           10194 non-null  float64
 15  Units           10194 non-null  int64
 16  Gross Profit    10194 non-null  float64
 17  Cost            10194 non-null  float64
dtypes: float64(3), int64(3), object(12)
memory usage: 1.4+ MB

In [ ]:
df.describe()

,Row ID,Customer ID,Sales,Units,Gross Profit,Cost
count,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000,10194.000000
mean,5097.500000,134468.961154,13.908537,3.791838,9.166451,4.742087
std,2942.898656,20231.483007,11.341020,2.228317,6.643740,5.061647
min,1.000000,100006.000000,1.250000,1.000000,0.250000,0.600000
25%,2549.250000,117212.000000,7.200000,2.000000,4.900000,2.400000
50%,5097.500000,133550.000000,10.800000,3.000000,7.470000,3.600000
75%,7645.750000,152051.000000,18.000000,5.000000,12.250000,5.700000
max,10194.000000,192314.000000,260.000000,14.000000,130.000000,130.000000

In [ ]:
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Country/Region    0
City              0
State/Province    0
Postal Code       0
Division          0
Region            0
Product ID        0
Product Name      0
Sales             0
Units             0
Gross Profit      0
Cost              0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
backup_path="/content/drive/MyDrive/Nassau_Candy_Project/data/raw/raw_backup.csv"

df.to_csv(backup_path,index=False)

print("Backup Created Successfully")

Backup Created Successfully

# S Initial Data Validation

## Objective

Before performing any analysis, we must verify the quality of the dataset.

This includes:

- Dataset dimensions
- Column names
- Data types
- Missing values
- Duplicate records
- Statistical summary
- Memory usage

This step ensures that the dataset is reliable for further analysis.

In [ ]:

# ==========================================
# Dataset Shape
rows, columns = df.shape

print("="*50)
print("📊 DATASET INFORMATION")
print("="*50)

print(f"Total Rows    : {rows}")
print(f"Total Columns : {columns}")

print("="*50)

==================================================
📊 DATASET INFORMATION
==================================================
Total Rows    : 10194
Total Columns : 18
==================================================

In [ ]:
# ==========================================
# Column Names
# ==========================================

print("Columns Present in Dataset:\n")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Columns Present in Dataset:

1. Row ID
2. Order ID
3. Order Date
4. Ship Date
5. Ship Mode
6. Customer ID
7. Country/Region
8. City
9. State/Province
10. Postal Code
11. Division
12. Region
13. Product ID
14. Product Name
15. Sales
16. Units
17. Gross Profit
18. Cost

In [ ]:
# ==========================================
#  Data Types
# ==========================================

datatype_df = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.values
})

datatype_df

            Column Data Type
0           Row ID     int64
1         Order ID    object
2       Order Date    object
3        Ship Date    object
4        Ship Mode    object
5      Customer ID     int64
6   Country/Region    object
7             City    object
8   State/Province    object
9      Postal Code    object
10        Division    object
11          Region    object
12      Product ID    object
13    Product Name    object
14           Sales   float64
15           Units     int64
16    Gross Profit   float64
17            Cost   float64

In [ ]:
# ==========================================
#  Missing Values
# ==========================================

missing = df.isnull().sum()

missing_df = pd.DataFrame({
    "Column": missing.index,
    "Missing Values": missing.values
})

missing_df

            Column  Missing Values
0           Row ID               0
1         Order ID               0
2       Order Date               0
3        Ship Date               0
4        Ship Mode               0
5      Customer ID               0
6   Country/Region               0
7             City               0
8   State/Province               0
9      Postal Code               0
10        Division               0
11          Region               0
12      Product ID               0
13    Product Name               0
14           Sales               0
15           Units               0
16    Gross Profit               0
17            Cost               0

In [ ]:
# ==========================================
#  Unique Values
# ==========================================

unique_df = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [df[col].nunique() for col in df.columns]
})

unique_df

            Column  Unique Values
0           Row ID          10194
1         Order ID           8549
2       Order Date            717
3        Ship Date           1338
4        Ship Mode              4
5      Customer ID           5044
6   Country/Region              2
7             City            542
8   State/Province             59
9      Postal Code            654
10        Division              3
11          Region              4
12      Product ID             15
13    Product Name             15
14           Sales             88
15           Units             14
16    Gross Profit            121
17            Cost             95

In [ ]:
# ==========================================
#  Memory Usage
# ==========================================

memory = df.memory_usage(deep=True) / 1024**2

memory_df = pd.DataFrame({
    "Column": memory.index,
    "Memory(MB)": memory.values
})

memory_df

            Column  Memory(MB)
0            Index    0.000126
1           Row ID    0.077774
2         Order ID    0.748575
3       Order Date    0.573584
4        Ship Date    0.573584
5        Ship Mode    0.601137
6      Customer ID    0.077774
7   Country/Region    0.601414
8             City    0.566859
9   State/Province    0.559051
10     Postal Code    0.524165
11        Division    0.562527
12          Region    0.544858
13      Product ID    0.602749
14    Product Name    0.756044
15           Sales    0.077774
16           Units    0.077774
17    Gross Profit    0.077774
18            Cost    0.077774

In [ ]:
# ==========================================
#  Numerical Summary
# ==========================================

df.describe().T

,count,mean,std,min,25%,50%,75%,max
Row ID,10194.0,5097.500000,2942.898656,1.00,2549.25,5097.50,7645.75,10194.0
Customer ID,10194.0,134468.961154,20231.483007,100006.00,117212.00,133550.00,152051.00,192314.0
Sales,10194.0,13.908537,11.341020,1.25,7.20,10.80,18.00,260.0
Units,10194.0,3.791838,2.228317,1.00,2.00,3.00,5.00,14.0
Gross Profit,10194.0,9.166451,6.643740,0.25,4.90,7.47,12.25,130.0
Cost,10194.0,4.742087,5.061647,0.60,2.40,3.60,5.70,130.0

In [ ]:
# ==========================================
#  Categorical Summary
# ==========================================

df.describe(include="object").T

                count unique                           top  freq
Order ID        10194   8549  US-2022-130974-CHO-SCR-58000     5
Order Date      10194    717                    02-09-2025    62
Ship Date       10194   1338                    07-06-2028    38
Ship Mode       10194      4                Standard Class  6120
Country/Region  10194      2                 United States  9994
City            10194    542                 New York City   915
State/Province  10194     59                    California  2001
Postal Code     10194    654                         10035   263
Division        10194      3                     Chocolate  9844
Region          10194      4                       Pacific  3253
Product ID      10194     15                 CHO-MIL-31000  2137
Product Name    10194     15    Wonka Bar - Milk Chocolate  2137

In [ ]:
# ==========================================
#  Data Quality Report
# ==========================================

quality_report = pd.DataFrame({
    "Metric": [
        "Rows",
        "Columns",
        "Missing Values",
        "Duplicate Rows"
    ],
    "Value": [
        df.shape[0],
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

quality_report

           Metric  Value
0            Rows  10194
1         Columns     18
2  Missing Values      0
3  Duplicate Rows      0

In [ ]:
# ==========================================
#  Save Report
# ==========================================

report_path = "/content/drive/MyDrive/Nassau_Candy_Project/reports/Data_Quality_Report.csv"

quality_report.to_csv(report_path, index=False)

print("✅ Data Quality Report Saved Successfully")
print(report_path)

✅ Data Quality Report Saved Successfully
/content/drive/MyDrive/Nassau_Candy_Project/reports/Data_Quality_Report.csv